///////////////////////////////////////////////////
// - Time.spanToIntLen is used repeatedly here to simplify getting the number bars for a given timeframe.
// - If "Minutes" or "Days" are selected, changing the timeframe on the chart, this indicator should still look about the same.
import Electrified/Time/7
// #require-exact ./Constants/MinutesDaysBars.pine
date = time('D')
var msPerBar = Time.bar()
var secondsPerBar = msPerBar / 1000
var minutesPerBar = secondsPerBar / 60
var timestampFormat = switch
    timeframe.isseconds => "{0,date,MM-dd hh:mm:ss}"
    timeframe.isminutes => "{0,date,MM-dd hh:mm}"
    => "{0,date,y-MM-dd}"